#TO USE
#ln -s ~/.config/bashrc/bashrc ~/.bashrc

#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='ls --color=auto'
alias grep='grep --color=auto'
#PS1='[\u@\h \W]\$ '
PS1="\[\033[1;34m\]\u@\h\[\033[0m\]:\[\033[01;32m\]\w\[\033[0m\]\$ "

neofetch
